Hero args decorator
slarkbot/slarkbot pull request #78
Opened 2021-04-14 20:28 UTC by connormullett

Closes issue #77. 

No functional changes, only refactoring and DRY'ing up commands.

2021-04-14 22:19 UTC, cschuijt requested changes
I have fixed the places I've commented on for your convenience. Things that jump out to me:
- /alias and /counter error message when giving no arguments uses the /build template
- /build, /counter and /alias give a double error message when no arguments are given

Fix these and it's merge ready as far as I'm concerned :)

2021-04-14 22:31 UTC, cschuijt commented
Closes #74 and #75

2021-04-15 13:48 UTC, connormullett commented on src/bot/decorators/require_hero_args_decorator.py
> +                constants.MISSING_ARGUMENT_MESSAGE % "/build <hero name or alias>"
Good catch, I've made MISSING_ARGUMENT_MESSAGE to be more generic and references the help command.

2021-04-15 15:29 UTC, cschuijt approved these changes
Should be all good now!

2021-04-16 02:49 UTC, merged